server:
  port: 5913

client:
  url: http://localhost
  port: 8080

db:
  url: localhost
  port: 27017
  dbName: blog
  connectionOptions:
    useNewUrlParser: true
    useUnifiedTopology: true

path:
  appData: /Users/sejin/Documents/blog-local
  image: /image
  logging: stdout
