server:
  port: 443

client:
  url: TBD
  port: TBD

db:
  url: TBD
  port: 27017
  dbName: blog
  connectionOptions:
    useNewUrlParser: true
    useUnifiedTopology: true

path:
  appData: /home/blog
  image: /image
  logging: /log
