server:
  port: 443

client:
  url: TBD
  port: TBD

db:
  uri: TBD
  connectionOptions:
    useNewUrlParser: true
    useUnifiedTopology: true
  retryCount: 1

path:
  appData: /home/blog
  image: /image
  logging: /log.txt
