server:
  port: 5913

client:
  url: http://localhost
  port: 8080

db:
  name: "blog"
  count: 1
  ip: "127.0.0.1"
  connectionOptions:
    useNewUrlParser: true
    useUnifiedTopology: true
  retryCount: 7

path:
  appData: ./appData
  image: /image
  logging: /log.txt
