server:
  port: 5913
  retryCount: 7

client:
  url: http://localhost
  port: 8080

db:
  url: localhost
  port: 27017
  dbName: blog
  connectionOptions:
    useNewUrlParser: true
    useUnifiedTopology: true

path:
  appData: ./appData
  image: /image
  logging: /log.txt
