name: Build & Testing

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      backend-path: ./backend

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ${{ env.backend-path }}/package-lock.json
      - name: '[backend] Preparation'
        run: |
          npm ci
          mkdir appData
        working-directory: ${{ env.backend-path }}
      - name: '[backend] Test'
        run: npm run coverage
        working-directory: ${{ env.backend-path }}
